### ISSUE TITLE
Яндекс разрывает соединение?

### ISSUE THREAD

**Issue by TomskDiver** [Angel777d/kodi.plugin.yandex-music#2]
Если перейти в радио и выбрать какое-либо то случится ошабка и радио не запустится. В логе:
```
2020-06-11 15:59:13.658 T:15260  NOTICE: [---] sys.argv: ['plugin://plugin.yandex-music/', '1', '', 'resume:false']
2020-06-11 15:59:13.658 T:15260  NOTICE: [---] codec: mp3, high_res: False
2020-06-11 15:59:30.924 T:7476 WARNING: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2020-06-11 16:00:38.800 T:9932 WARNING: Previous line repeats 6 times.
2020-06-11 16:00:38.800 T:9932  NOTICE: [---] sys.argv: ['plugin://plugin.yandex-music/', '2', '?mode=login&title=Login', 'resume:false']
2020-06-11 16:00:38.800 T:9932  NOTICE: [---] codec: mp3, high_res: False
2020-06-11 16:00:56.645 T:9932  NOTICE: [---] build playlist item. tracks: 0
2020-06-11 16:03:03.989 T:10228  NOTICE: Previous line repeats 6 times.
2020-06-11 16:03:03.989 T:10228  NOTICE: [---] sys.argv: ['plugin://plugin.yandex-music/', '3', '?mode=radio&title=Radio', 'resume:false']
2020-06-11 16:03:03.989 T:10228  NOTICE: [---] codec: mp3, high_res: False
2020-06-11 16:03:08.855 T:12024  NOTICE: [---] sys.argv: ['plugin://plugin.yandex-music/', '4', '?mode=radio_station&radio_type=dashboard&station_key=tomskdiver&title=%3f%3f%3f%3f%3f%3f%3f%3f%3f', 'resume:false']
2020-06-11 16:03:08.855 T:12024  NOTICE: [---] codec: mp3, high_res: False
2020-06-11 16:03:09.248 T:8000   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.yandex-music/?mode=radio_station&radio_type=dashboard&station_key=tomskdiver&title=%3f%3f%3f%3f%3f%3f%3f%3f%3f
2020-06-11 16:03:09.260 T:3044 WARNING: CPythonInvoker(5): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
2020-06-11 16:03:09.263 T:7476   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.yandex-music/?mode=radio_station&radio_type=dashboard&station_key=tomskdiver&title=%3f%3f%3f%3f%3f%3f%3f%3f%3f) failed
2020-06-11 16:03:09.421 T:3044  NOTICE: [Radio Service] Started
2020-06-11 16:03:09.421 T:3044  NOTICE: [Radio Service] ['service.py', 'radio', 'dashboard', 'tomskdiver']
2020-06-11 16:03:13.062 T:3044   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'yandex_music.exceptions.NetworkError'>
                                            Error Contents: ('Connection aborted.', BadStatusLine("''",))
                                            Traceback (most recent call last):
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\service.py", line 136, in <module>
                                                player.start(station.getId(), station.source.station.id_for_from)
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\service.py", line 31, in start
                                                self.result = radio.start_radio(client, self.station_id, self.station_from)
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\radio.py", line 29, in start_radio
                                                play_id = do_play_start(client, current, station_id, batch_id)
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\radio.py", line 78, in do_play_start
                                                end_position_seconds=total_seconds,
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\lib/yandex-music-api/yandex_music\client.py", line 35, in wrapper
                                                result = method(*args, **kwargs)
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\lib/yandex-music-api/yandex_music\client.py", line 612, in play_audio
                                                result = self._request.post(url, data, timeout=timeout, *args, **kwargs)
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\lib/yandex-music-api/yandex_music\utils\request.py", line 138, in post
                                                timeout=timeout, *args, **kwargs)
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\lib/yandex-music-api/yandex_music\utils\request.py", line 107, in _request_wrapper
                                                raise NetworkError(e)
                                            NetworkError: ('Connection aborted.', BadStatusLine("''",))
                                            -->End of Python script error report<--
```

Если перейти например в плейлист дня, то он загрузится, но всё равно случится ошибка:
```
2020-06-11 16:07:03.913 T:13264  NOTICE: [---] sys.argv: ['plugin://plugin.yandex-music/', '5', '?mode=login&title=Login', 'resume:false']
2020-06-11 16:07:03.913 T:13264  NOTICE: [---] codec: mp3, high_res: False
2020-06-11 16:07:05.454 T:13264  NOTICE: [---] build playlist item. tracks: 0
2020-06-11 16:07:08.098 T:11636  NOTICE: Previous line repeats 6 times.
2020-06-11 16:07:08.098 T:11636  NOTICE: [---] sys.argv: ['plugin://plugin.yandex-music/', '6', '?mode=playlist&playlist_id=503646255%3a49808932&title=%3f%3f%3f%3f%3f%3f%3f%3f%20%3f%3f%3f', 'resume:false']
2020-06-11 16:07:08.098 T:11636  NOTICE: [---] codec: mp3, high_res: False
2020-06-11 16:07:09.911 T:11636   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'yandex_music.exceptions.NetworkError'>
                                            Error Contents: ('Connection aborted.', BadStatusLine("''",))
                                            Traceback (most recent call last):
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\plugin.py", line 581, in <module>
                                                main()
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\plugin.py", line 429, in main
                                                build_playlist(client, playlist_id)
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\plugin.py", line 316, in build_playlist
                                                sendPlayTrack(client, tracks[0])
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\plugin.py", line 515, in sendPlayTrack
                                                end_position_seconds=track.duration_ms / 1000,
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\lib/yandex-music-api/yandex_music\client.py", line 35, in wrapper
                                                result = method(*args, **kwargs)
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\lib/yandex-music-api/yandex_music\client.py", line 612, in play_audio
                                                result = self._request.post(url, data, timeout=timeout, *args, **kwargs)
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\lib/yandex-music-api/yandex_music\utils\request.py", line 138, in post
                                                timeout=timeout, *args, **kwargs)
                                              File "C:\Users\Diver\AppData\Roaming\Kodi\addons\plugin.yandex-music\lib/yandex-music-api/yandex_music\utils\request.py", line 107, in _request_wrapper
                                                raise NetworkError(e)
                                            NetworkError: ('Connection aborted.', BadStatusLine("''",))
                                            -->End of Python script error report<--
```

Но песню запустить даст. Хотелось бы всё таки чтобы радио работало.

**Comment by Angel777d** [comment]
Аха. Что то новое. Доберусь гляну

**Comment by Angel777d** [comment]
Нашел, поправил, залил свежую сборку
