### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by crvux** [Angel777d/kodi.plugin.yandex-music#6]
После логина не удаётся запустить плагин. 

```
2020-09-22 16:06:09.264 T:1937718704   ERROR: Control 55 in window 10502 has been asked to focus, but it can't
2020-09-22 16:06:10.221 T:1807721344  NOTICE: [---] sys.argv: ['plugin://plugin.yandex-music/', '50', '', 'resume:false']
2020-09-22 16:06:10.221 T:1807721344  NOTICE: [---] codec: mp3, high_res: False
2020-09-22 16:06:10.931 T:1807721344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'uid'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.yandex-music/plugin.py", line 670, in <module>
                                                main()
                                              File "/storage/.kodi/addons/plugin.yandex-music/plugin.py", line 493, in main
                                                build_main(authorized, client)
                                              File "/storage/.kodi/addons/plugin.yandex-music/plugin.py", line 212, in build_main
                                                entry_list += [build_item_playlist(playlist) for playlist in playlists]
                                              File "/storage/.kodi/addons/plugin.yandex-music/plugin.py", line 147, in build_item_playlist
                                                url = build_url({'mode': 'playlist', 'playlist_id': playlist.playlist_id, 'title': playlist.title})
                                              File "/storage/.kodi/addons/plugin.yandex-music/lib/yandex-music-api/yandex_music/playlist/playlist.py", line 98, in playlist_id
                                                return '%s:%s' % (self.owner.uid, self.kind)
                                            AttributeError: 'NoneType' object has no attribute 'uid'
                                            -->End of Python script error report<--
2020-09-22 16:06:12.342 T:1596339072   ERROR: GetDirectory - Error getting plugin://plugin.yandex-music/
2020-09-22 16:06:12.342 T:1937718704   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.yandex-music/) failed
```

**Comment by Angel777d** [comment]
хмм.
У меня такой проблемы нет.
Если можно, было бы неплохо попробовать с Вашим токеном. На почту прислать например.

**Comment by crvux** [comment]
Присылаю открыто: `AgAAAABGgjhvAAG8XgepbDBU00Junr-H2gUJjkk`.
Аккаунт создавался для прослушивания музыки через плагин.

**Comment by Angel777d** [comment]
да, с этим падает.
разберемся.

**Comment by Angel777d** [comment]
Проблема связана с тем, что аккаунт совсем новый
На нем еще нет ни плейлистов, ничего
Можно зайти на страничку я.музыки в браузере, пожмякать там все что нужно и будет работать.
Обновил плагин.
Починть с ходу удалось не все, но именно так больше не падает.
