### ISSUE TITLE
Kodi 19 не работает поиск/mixes

### ISSUE THREAD

**Issue by msazanov** [Angel777d/kodi.plugin.yandex-music#9]
<details>
  <summary>Лог ошибки при поиске:</summary>

2021-09-07 12:47:27.408 T:61786    INFO <general>: initializing python engine.
2021-09-07 12:47:27.821 T:61786 WARNING <general>: [---] codec: mp3, high_res: False
2021-09-07 12:47:28.131 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:28.131 T:61786   ERROR <general>: Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': True}
                                                   
2021-09-07 12:47:28.131 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:28.131 T:61786   ERROR <general>: Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'userhash': '6425e1daae9aeec569c29c156ccc8da1b310e40462f836355a13b621f9df02d6'}
                                                   
2021-09-07 12:47:28.131 T:61786 WARNING <general>: [---] [Yandex music plugin] authorized: True, mode: ['search'], args: {'mode': ['search'], 'title': ['Search']}
2021-09-07 12:47:46.381 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.381 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.381 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.381 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.381 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.381 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.382 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.383 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.384 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.385 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'COVER_ONLY'}
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'track_sharing_flag': 'VIDEO_ALLOWED'}
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'podcast_episode_type': 'full', 'track_sharing_flag': 'VIDEO_ALLOWED'}
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:46.386 T:61786   ERROR <general>: Type: <class 'yandex_music.track.track.Track'>; kwargs: {'podcast_episode_type': 'full', 'track_sharing_flag': 'VIDEO_ALLOWED'}
                                                   
2021-09-07 12:47:46.387 T:61786   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'order'
                                                   Traceback (most recent call last):
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 666, in <module>
                                                       main()
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 511, in main
                                                       build_search(client)
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 421, in build_search
                                                       results = getSortedResults(client.search(searchString))
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 627, in getSortedResults
                                                       tmp = [(getattr(search, field).order, field) for field in fields]
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 627, in <listcomp>
                                                       tmp = [(getattr(search, field).order, field) for field in fields]
                                                   AttributeError: 'NoneType' object has no attribute 'order'
                                                   -->End of Python script error report<--
                                                   
2021-09-07 12:47:46.435 T:61786    INFO <general>: Python interpreter stopped
2021-09-07 12:47:46.444 T:61784   ERROR <general>: GetDirectory - Error getting plugin://plugin.yandex-music/?mode=search&title=Search
2021-09-07 12:47:46.457 T:61357   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.yandex-music/?mode=search&title=Search) failed
2021-09-07 12:47:46.496 T:61813    INFO <general>: initializing python engine.
2021-09-07 12:47:46.853 T:61813 WARNING <general>: [---] codec: mp3, high_res: False
2021-09-07 12:47:47.254 T:61813   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:47.254 T:61813   ERROR <general>: Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': True}
                                                   
2021-09-07 12:47:47.255 T:61813   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:47.255 T:61813   ERROR <general>: Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'userhash': '6425e1daae9aeec569c29c156ccc8da1b310e40462f836355a13b621f9df02d6'}
                                                   
2021-09-07 12:47:47.255 T:61813 WARNING <general>: [---] [Yandex music plugin] authorized: True, mode: None, args: {}
2021-09-07 12:47:47.534 T:61815   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:47.535 T:61815   ERROR <general>: Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': True}
                                                   
2021-09-07 12:47:47.535 T:61815   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:47.535 T:61815   ERROR <general>: Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'userhash': '6425e1daae9aeec569c29c156ccc8da1b310e40462f836355a13b621f9df02d6'}
                                                   
2021-09-07 12:47:47.726 T:61813    INFO <general>: CPythonInvoker(23, /home/random/.kodi/addons/plugin.yandex-music/plugin.py): script successfully run
2021-09-07 12:47:47.726 T:61813    INFO <general>: CPythonInvoker(23, /home/random/.kodi/addons/plugin.yandex-music/plugin.py): waiting on thread 140242803738368
2021-09-07 12:47:48.275 T:61815   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:47:48.275 T:61815   ERROR <general>: Type: <class 'yandex_music.account.plus.Plus'>; kwargs: {'migrated': False}
                                                   
2021-09-07 12:47:48.403 T:61813    INFO <general>: Python interpreter stopped

</details>

<details>
  <summary>Лог ошибки при открытии mixes:</summary>
2021-09-07 12:48:55.003 T:61855    INFO <general>: initializing python engine.
2021-09-07 12:48:55.366 T:61855 WARNING <general>: [---] codec: mp3, high_res: False
2021-09-07 12:48:55.778 T:61855   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:48:55.778 T:61855   ERROR <general>: Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': True}
                                                   
2021-09-07 12:48:55.778 T:61855   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:48:55.778 T:61855   ERROR <general>: Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'userhash': '6425e1daae9aeec569c29c156ccc8da1b310e40462f836355a13b621f9df02d6'}
                                                   
2021-09-07 12:48:55.778 T:61855 WARNING <general>: [---] [Yandex music plugin] authorized: True, mode: ['mixes'], args: {'mode': ['mixes'], 'title': ['Mixes']}
2021-09-07 12:48:56.442 T:61855   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 666, in <module>
                                                       main()
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 504, in main
                                                       build_mixes(client)
                                                     File "/home/random/.kodi/addons/plugin.yandex-music/plugin.py", line 231, in build_mixes
                                                       tag = mix.data.url.split("/")[2].split("?")[0].encode("utf-8")
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2021-09-07 12:48:56.497 T:61855    INFO <general>: Python interpreter stopped
2021-09-07 12:48:56.512 T:61853   ERROR <general>: GetDirectory - Error getting plugin://plugin.yandex-music/?mode=mixes&title=Mixes
2021-09-07 12:48:56.524 T:61357   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.yandex-music/?mode=mixes&title=Mixes) failed
2021-09-07 12:48:56.563 T:61858    INFO <general>: initializing python engine.
2021-09-07 12:48:56.954 T:61858 WARNING <general>: [---] codec: mp3, high_res: False
2021-09-07 12:48:57.224 T:61858   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:48:57.224 T:61858   ERROR <general>: Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': True}
                                                   
2021-09-07 12:48:57.224 T:61858   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:48:57.224 T:61858   ERROR <general>: Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'userhash': '6425e1daae9aeec569c29c156ccc8da1b310e40462f836355a13b621f9df02d6'}
                                                   
2021-09-07 12:48:57.224 T:61858 WARNING <general>: [---] [Yandex music plugin] authorized: True, mode: None, args: {}
2021-09-07 12:48:57.669 T:61860   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:48:57.670 T:61860   ERROR <general>: Type: <class 'yandex_music.account.subscription.Subscription'>; kwargs: {'had_any_subscription': True}
                                                   
2021-09-07 12:48:57.670 T:61860   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:48:57.670 T:61860   ERROR <general>: Type: <class 'yandex_music.account.status.Status'>; kwargs: {'pretrial_active': False, 'userhash': '6425e1daae9aeec569c29c156ccc8da1b310e40462f836355a13b621f9df02d6'}
                                                   
2021-09-07 12:48:58.093 T:61858    INFO <general>: CPythonInvoker(25, /home/random/.kodi/addons/plugin.yandex-music/plugin.py): script successfully run
2021-09-07 12:48:58.094 T:61858    INFO <general>: CPythonInvoker(25, /home/random/.kodi/addons/plugin.yandex-music/plugin.py): waiting on thread 140244775073536
2021-09-07 12:48:59.137 T:61860   ERROR <general>: Found unknown fields received from API! Please copy warn message and send to https://bit.ly/3dsFxyH (github issue), thank you!
                                                   
2021-09-07 12:48:59.137 T:61860   ERROR <general>: Type: <class 'yandex_music.account.plus.Plus'>; kwargs: {'migrated': False}
                                                   
2021-09-07 12:48:59.272 T:61858    INFO <general>: Python interpreter stopped

  </details>
  
  Поиск и mixes не работает.
Версия kodi 19.1
пробовал запускать на rpi4 libreelec и x86 linux

**Comment by Angel777d** [comment]
Понял, смотрю

**Comment by Angel777d** [comment]
По сути это 2 разных бага:
1. в поиске теперь приходят пустые поля, типа video: None. 
2. в миксах кроме тегов появились новые сущности (kids и что то еще). Их пока просто отрезал.
Залил свежую версию (0.1.4)

**Comment by msazanov** [comment]
Огромное спасибо! Завтра протестирую на своих платформах! Всех благ!

**Comment by Angel777d** [comment]
Обращайтесь )
